### ISSUE TITLE
Allow easier styling of the Set / Close buttons 

### ISSUE THREAD

**Issue by welshcathy** [logisticinfotech/ionic4-datepicker#10]
I'd like to be able to change the button type and styles of Set and Close buttons.
e.g. to use outline buttons not solid ones.

I'd also like to be able to switch them over from Close / Set to Set / Close.

**Comment by chintan13** [comment]
If we move close button to top would that work?
or close button looks good in UI?

**Comment by chintan13** [comment]
In Version 1.1.2 there is now two new option for this things

**btnCloseSetInReverse**: true, default false
**btnProperties**: {
        expand: 'block', // "block" | "full"
        fill: '', // "clear" | "default" | "outline" | "solid"
        size: '', // "default" | "large" | "small"
        disabled: '', // boolean (default false)
        strong: '', // boolean (default false)
        color: ''  // "primary", "secondary", "tertiary", "success", "warning", "danger", "light", "medium", "dark" , and give color in string
      }

I hope this should satisfy your requirement

**Comment by welshcathy** [comment]
Brilliant!! Thank you :)
