### ISSUE TITLE
Set a different colour scheme to the date picker

### ISSUE THREAD

**Issue by welshcathy** [logisticinfotech/ionic4-datepicker#12]
I'd like to be able to set a different ion-color-* to the date picker.
My current primary colour scheme does not work well with the picker.

I'd like to either 
- be able to set a color property to the picker 
- have access to css-variables to style individual components of the picker

**Comment by chintan13** [comment]
You can do css like below and you will be able to design it as per your requirement.
All ionic component variable is applicable directly in this way.

```
.li-ionic4-datePicker {
    .modal-wrapper {
        height: 75%;
        max-height: 478px;
        width: 310px;
        border-radius: 0px;
        --ion-color-primary: red; // This Variable used for the change of color ion-datepicker only.
        --ion-color-primary-tint: rgb(214, 153, 153); // This Variable changes the tint color of background when click button.

        ion-button {
            --ion-color-primary: green;
            --ion-color-primary-tint: lightgreen;
            // button customization css write here...
        }

        @media (min-width: 768px) {
            width: 350px;
            height: 65%;
        }
    }
}
```

**Comment by welshcathy** [comment]
Thanks for the reply!
That gives some flexibility .. but it's not quite enough for what I need.

Because you have used !important all through the css I cannot do things like have one colour for the tool bar and a different colour for the selected date background. 
They are both set to `var(--ion-color-primary)!important`  :(

Can you take out the !important statements as they are not needed?
Then it would be really easy for us to have complete freedom :)

( The trouble is that the designer has come up with a non white background which means I must have different colours for the toolbar, selected date etc).

**Comment by welshcathy** [comment]
Ah of course I can do this tho! Perfect!

        ion-toolbar {
          --ion-color-primary: tomato;
        }
