### ISSUE TITLE
build issue with Prod mode

### ISSUE THREAD

**Issue by cymxiao** [logisticinfotech/ionic4-datepicker#13]
Dear sir,

I have this error when  I run the command:    ionic cordova build ios --prod 
the error is : 
ERROR in ./dist/ionic4-datepicker/logisticinfotech-ionic4-datepicker.ngfactory.js
Module not found: Error: Can't resolve '@logisticinfotech/ionic4-datepicker' in '/Users/cym/Documents/03.ionic/ionic4-datepicker/dist/ionic4-datepicker'

I've update the ionic 4 to latest version 4.10.3.

**Comment by chintan13** [comment]
I have checked with latest ionic version 4.10.3, created new ionic project and added date picker to it. Then created build with same command ionic cordova build ios --prod    It works fine for me.

can you check if you are using latest version of this datepicker?
or can you provide me demo project to expriment with it?

**Comment by chintan13** [comment]
since we are not able to regenerate this issue, closing for now.
