### ISSUE TITLE
Open date picker on button click

### ISSUE THREAD

**Issue by skandaapriya** [logisticinfotech/ionic4-datepicker#14]
Open date picker on button click

**Comment by chintan13** [comment]
so can you please explain your use case, how you would like to get data back if we open up datepicker from button? currently we are sending data back to ngModel or formControl

**Comment by skandaapriya** [comment]
Hi,
I have button next to textbox. On click of button I would like to see
datepicker popup.
Once date selected, selected date should added to textbox value.

Regards,
Rekha

**Comment by chintan13** [comment]
For this you just need to do as below, this should give you full control over it.
`
import { Ionic4DatepickerModalComponent } from 'ionic4-datepicker';
import { ModalController } from '@ionic/angular';
constructor(
    public modalCtrl: ModalController
) { }

async openDatePicker() {
    const datePickerModal = await this.modalCtrl.create({
      component: Ionic4DatepickerModalComponent,
      cssClass: 'li-ionic4-datePicker',
      componentProps: { 'objConfig': this.datePickerObjPtBr }
    });
    await datePickerModal.present();

    datePickerModal.onDidDismiss()
      .then((data) => {
        // this.isModalOpen = false;
        console.log(data);
        this.selectedDate = data.data.date;
      });
  }
`

**Comment by skandaapriya** [comment]
Hi,

Thank you very much.

Regards,
Rekha

**Comment by skandaapriya** [comment]
Hi,
I tried opening as modal, but results as below
[image: image.png]
 import { Ionic4DatepickerModalComponent } from 'ionic4-datepicker';

import { ModalController } from '@ionic/angular';
constructor(
public modalCtrl: ModalController
) { }
datePickerObj: any = {
closeOnSelect: true,
titleLabel: 'Datum',
todayLabel: 'Heute',
closeLabel: 'Schließen',
monthsList: [
'Jan',
'Feb',
'March',
'April',
'May',
'June',
'July',
'Aug',
'Sept',
'Oct',
'Nov',
'Dec'
],
weeksList: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
dateFormat: 'DD.MM.YYYY'
};

async openDatePicker() {
const datePickerModal = await this.modalCtrl.create({
component: Ionic4DatepickerModalComponent,
cssClass: 'li-ionic4-datePicker',
componentProps: { 'objConfig': this.datePickerObjPtBr }
});
await datePickerModal.present();
const confirmationResult = await modal.onDidDismiss();
if (confirmationResult.data !== undefined) {
const dateTime = moment(
confirmationResult.data.date,
'DD.MM.YYYY'
)
.format('YYYY.MM.DD');
}
}

Regards,
Rekha

**Comment by skandaapriya** [comment]
Can you please update me on the above problem?

**Comment by chintan13** [comment]
I don't see image and not able to get your problem, can you post image and explain little more?

**Comment by skandaapriya** [comment]
Hi,

I have done the coding similarly as you explained but i dont see the text
in calendar control. Please find attachment for the same.

Regards,
Rekha
