### ISSUE TITLE
Set month and year

### ISSUE THREAD

**Issue by skandaapriya** [logisticinfotech/ionic4-datepicker#15]
Set month and year in date picker

**Comment by chintan13** [comment]
can you explain little bit more for this? currently we are able to set date by which it displays that month and year.

**Comment by skandaapriya** [comment]
Hi,

By default current year and month will set in date picker. Correct?
But I want set the month and year of my wish.
For ex: Current month is Feb year 2019.
But when date picker pops up I want to see Jan 2018. How to achieve this?

Regards,
Rekha

**Comment by chintan13** [comment]
in version 1.1.2 there is option for **inputDate**

this will be considered date in case there is no default date provided

**Comment by skandaapriya** [comment]
Hi,

Thank you very much.

Regards,
Rekha
