### ISSUE TITLE
Change the icons on the next / previous month buttons 

### ISSUE THREAD

**Issue by welshcathy** [logisticinfotech/ionic4-datepicker#17]
We have an issue with the way our web server is set up that means we cannot use ionicons. It's a cloud platform and not a real web server so there is no easy way around this problem.

To work around this all our ion-icons use the src attribute to point at the icon svg file directly.

In the date picker this means that the next / previous month buttons are invisible as the arrow icons fail to resolve properly.

It would be great if you could add a configuration property to allow us to define custom image src to use for these buttons!

**Comment by chintan13** [comment]
ok sure I will find best way around it, but cant you just place svg where its looking by default? or just override it with css?

**Comment by welshcathy** [comment]
Thank you for having a look! Unfortunately it's a 'cloud web server' that does crazy redirects, not a real web server so I have no way of doing that :(
I am looking to see if I can set up redirects for these resources ... but again it's all hidden in the cloud :( I know that CSS can change SVG properties, but I can't think how CSS could override the ion-icon src image that is used, especially if it failed to resolve to a file in the first place??

**Comment by chintan13** [comment]
arrowNextPrev: {
        nextArrowSrc: 'assets/images/arrow_right.svg',
        prevArrowSrc: 'assets/images/arrow_left.svg'
      } // This object supports only SVG files.

you can now pass src :)

**Comment by welshcathy** [comment]
That works perfectly!! Thank you again for taking the time to look at this for me - it's much appreciated :)

**Comment by chintan13** [comment]
send me some screenshot of it, just to know how you guys have designed it and how it looks :)
