### ISSUE TITLE
Can't construct a query for the property "content" of "Ionic4DatepickerModalComponent" since the query selector wasn't defined

### ISSUE THREAD

**Issue by blakezeisler** [logisticinfotech/ionic4-datepicker#18]
I perform Step1: Install. `npm i @logisticinfotech/ionic4-datepicker moment`
Then after Step2: Import it in your module and in import array. I get the following error upon Ionic Serve.
 

> Can't construct a query for the property "content" of "Ionic4DatepickerModalComponent" since the query selector wasn't defined

My dependencies:
```
dependencies": {
    "@angular/common": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "@ionic-native/core": "5.0.0-beta.21",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-beta.17",
    "@logisticinfotech/ionic4-datepicker": "^1.3.0",
    "angularfire2": "^5.1.3",
    "core-js": "^2.6.5",
    "cors": "^2.8.5",
    "firebase": "^5.11.1",
    "moment": "^2.24.0",
    "rxjs": "~6.3.3",
    "zone.js": "^0.8.29"
  }

```

**Comment by blakezeisler** [comment]
I can't seem to get it working. I run npm install command, then Import it into my app.module.ts and list it in my Imports, as soon as i save my served app get the error i listed above. Is there a better step by step example. I seem to be missing something...

**Comment by chintan13** [comment]
can you give me example repo or something to check with?

**Comment by blakezeisler** [comment]
It had to do with my lazy loading, I ended up using the Angular Material Datepicker component instead

**Comment by blakezeisler** [comment]
I ended up using Angular Material Datepicker for my purpose.
