### ISSUE TITLE
make calender can slide to change calendar page

### ISSUE THREAD

**Issue by auron105** [logisticinfotech/ionic4-datepicker#19]
hi
 i use ionic4-datepicker in my app, is great~!
but i want add slide like ion-slide.
does it work?
thx~

**Comment by digvijayLogistic** [comment]
Hello, @auron105 

Nice suggestion! but I am afraid it will increase much load on datepicker component, so we are not planning to add this feature yet.

Of course, we will help you if you Fork and start implementing it.
