### ISSUE TITLE
Year descending

### ISSUE THREAD

**Issue by ewankobkt** [logisticinfotech/ionic4-datepicker#2]
I read the documents, but I don't see a year in descending order. Is there something I missed? Thanks.

**Comment by chintan13** [comment]
are you looking for new feature in it? can you explain your requirement with screenshot?

**Comment by chintan13** [comment]
I have settled by default from maxyear to minyear 👍

**Comment by ewankobkt** [comment]
Thanks for complying to the issues.

Is there a way that you can set the option of the year to ascending or descending?

**Comment by chintan13** [comment]
oh there is no way currently for it, but I will try to put this feature in next release which should be in couple of days.

**Comment by ewankobkt** [comment]
Thanks a lot for fixing the issues.  👍
