### ISSUE TITLE
Required full working sample

### ISSUE THREAD

**Issue by daijaafarflyt** [logisticinfotech/ionic4-datepicker#20]
Can you include in the doc of full code working sample?, instead of snippet code here and there. Unable to follow the doc from https://www.logisticinfotech.com/blog/ionic4-datepicker-component due to inconsistent method name and variable declaration

**Comment by digvijayLogistic** [comment]
Please refer this below link, for example, of ionic4-datepicker: 

https://github.com/logisticinfotech/ionic4-datepicker-example
