### ISSUE TITLE
Select multiple dates

### ISSUE THREAD

**Issue by cunla** [logisticinfotech/ionic4-datepicker#21]
Add support to set/select multiple dates

**Comment by kisimediaDE** [comment]
Whould be a nice feature

**Comment by chintan13** [comment]
ok, can you guys elaborate more on this feature suggestion?

**Comment by kisimediaDE** [comment]
I don't know what was the intention from @cunla but I thought about this: 

- Add a option like "selectRange: true"
- Click on the day you want to start and on the date you want to end
- Get back an array with start and enddate

Example: https://jsfiddle.net/salman/fa18g5u2/

Another way would be this: 

- Add a option like "selectMultiple: true"
- Click on every day you want to select
- Get back an array with every selected day

Example: https://jsfiddle.net/christianklemp_imt/b20paum2/

**Comment by cunla** [comment]
exactly what @kisimediaDE said.

**Comment by chintan13** [comment]
Sorry due to complexity we are dropping this idea at the moment
