### ISSUE TITLE
Can't bind to 'liIonic4Datepicker' since it isn't a known property of 'ion-input'.

### ISSUE THREAD

**Issue by sohail0992** [logisticinfotech/ionic4-datepicker#22]
I am using ionic 4 and `Ionic4DatepickerModule` is imported in app module 
```
<ion-input readonly [(ngModel)]="currentQuestion.datePicker" 
      [liIonic4Datepicker]="datePickerObj" 
      (ionchange)="myFunction()">
 </ion-input>
```

**Comment by kirillusgadus** [comment]
Did you add to page module?
```
    imports: [
        CommonModule,
        FormsModule,
        IonicModule,
        RouterModule.forChild(routes),
        ReactiveFormsModule,
       //this --> Ionic4DatepickerModule,
    ],
```

**Comment by sohail0992** [comment]
> Did you add to page module?
> 
> ```
>     imports: [
>         CommonModule,
>         FormsModule,
>         IonicModule,
>         RouterModule.forChild(routes),
>         ReactiveFormsModule,
>        //this --> Ionic4DatepickerModule,
>     ],
> ```

Yes

**Comment by chintan13** [comment]
Please check implementation in this repo and see what is the difference:
https://github.com/logisticinfotech/ionic4-datepicker-example
