### ISSUE TITLE
Can pick date over year of 2020

### ISSUE THREAD

**Issue by sahyun1** [logisticinfotech/ionic4-datepicker#24]
I can only select upto 2010, is this what's expected?
![image](https://user-images.githubusercontent.com/3164033/59578252-6b309000-911b-11e9-8c6e-d52f9d579643.png)

**Comment by sahyun1** [comment]
ok, by setting toDate to in the future, problem solved.
I think this is quite normal behaviour.

**Comment by Robertjr1992** [comment]
@sahyun1 does it worked for you by setting toDate to in the future if yes can you tell me the version which you are using as I'm having an issue it's not showing the future years

**Comment by sahyun1** [comment]
@Robertjr1992 
yes it's still working, I'm using v1.4.3

This is snippet from my code
```
const datePickerObj = {
      mondayFirst: true, // default false
      closeOnSelect: true,
      toDate: new Date('2040-12-31'),
      inputDate: moment(date).format('DD-MM-YYYY'),
      titleLabel: 'Select a Date', // default null
      dateFormat: 'DD-MM-YYYY', // default null
      monthsList: ['Jan', 'Feb', 'March', 'April', 'May', 'June', 'July', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec'],
      weeksList: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
      showTodayButton: true
    };


    const datePickerModal = await this._modalCtrl.create({
      component: Ionic4DatepickerModalComponent,
      backdropDismiss: false,
      mode: 'md',
      cssClass: 'li-ionic4-datePicker',
      componentProps: {'objConfig': datePickerObj}
    });
```

**Comment by Robertjr1992** [comment]
@sahyun1 does it work for iOS because I'm only having an issue with iOS device I tried to debug and getting error in iOS debugger I tried both 1.4.3 and 1.4.4 same issue
<img width="1020" alt="Screenshot 2020-10-20 at 2 35 35 PM" src="https://user-images.githubusercontent.com/69619444/96565086-86984600-12e1-11eb-91bf-b13746b4892f.png">
e

**Comment by sahyun1** [comment]
By looking at the error I think your issue is not toDate. Get it working first then add toDate

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
