### ISSUE TITLE
 Extend peer dependencies to Angular 8

### ISSUE THREAD

**Issue by alvaro-octal** [logisticinfotech/ionic4-datepicker#25]
**Issue description**

running `npm install` throws the following warning:

```
npm WARN @logisticinfotech/ionic4-datepicker@1.3.0 requires a peer of @angular/common@^7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @logisticinfotech/ionic4-datepicker@1.3.0 requires a peer of @angular/core@^7.2.0 but none is installed. You must install peer dependencies yourself.
```
**Steps to reproduce and a minimal demo of the problem**

`npm install` with Angular 8

**Current behavior**

`npm install` shows a couple of warning due to peer dependencies.

**Expected/desired behavior**

No warnings should be shown

**Comment by chintan13** [comment]
So we should remove peer dependancy at all from the package.json ?
do you have any suggestion on it?
