### ISSUE TITLE
ERROR in There is no format with import statement

### ISSUE THREAD

**Issue by Manvender-TC** [logisticinfotech/ionic4-datepicker#26]
**Build Failing :**

ERROR in There is no format with import statements in '
```
.../node_modules/ionic4-date-picker' entry-point.
[ERROR] An error occurred while running subprocess ng.
```

   ionic (Ionic CLI)             : 4.12.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0-dev.201906192117.6727cfc
   @angular-devkit/build-angular : 0.800.3
   @angular-devkit/schematics    : 8.0.3
   @angular/cli                  : 8.0.3
   @ionic/angular-toolkit        : 1.4.1

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.19
   @capacitor/core           : 1.0.0-beta.19

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (../)
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.18

**Comment by chintan13** [comment]
can you give me minimal repo to test/regenerate this issue?

**Comment by chintan13** [comment]
Closes as no answer from issue generator
