### ISSUE TITLE
Unable to open date picker after clicking outside the calendar on load

### ISSUE THREAD

**Issue by lukasnys** [logisticinfotech/ionic4-datepicker#28]
When clicking outside the calendar before the date picker is completely done loading, it leaves the user unable to reopen the date picker.

**Comment by chintan13** [comment]
would you like to provide video for this issue?

**Comment by lukasnys** [comment]
https://gyazo.com/624028295981ae31a9d171b04588476c

The first time I show it works, then the second time I make it break. As soon as it stops opening, you have to refresh the page to make it open again.

**Comment by chintan13** [comment]
We found the issue and solved it in version 1.4.1
so please upgrade to this version and try again.
