### ISSUE TITLE
Week is changing after repeated opening of calendar

### ISSUE THREAD

**Issue by ewankobkt** [logisticinfotech/ionic4-datepicker#3]
The order of the week in the calendar is changing after I constantly click/tap the input.

![bug](https://user-images.githubusercontent.com/17458597/51379739-12000880-1b4b-11e9-83e5-781b1d97c4ac.gif)

I don't have any errors on my console. This is my options:

`this.datePickerObj = {
      fromDate: new Date('1900-01-01'), // need this in order to have toDate
      toDate: new Date('2018-01-01'),
      showTodayButton: false,
      closeOnSelect: true,
      disableWeekDays: [],
      mondayFirst: true,
      setLabel: 'Select a Date', 
      todayLabel: 'Today',
      closeLabel: 'Close',
      disabledDates: [],
      titleLabel: 'Select a Date',
      monthsList: ["Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"],
      weeksList: ["S", "S", "M", "T", "W", "T", "F"],
      dateFormat: 'MMMM d, yyyy',
      clearButton: false
    };
  }`

**Comment by cymxiao** [comment]
I have same issue.  The week is changing after the popup closed.

**Comment by chintan13** [comment]
should be fixed in last commit and version 1.0.6 let me know you find anything else
