### ISSUE TITLE
Unreachable dates on device landscape mode and full screen modal

### ISSUE THREAD

**Issue by Arieru** [logisticinfotech/ionic4-datepicker#34]
When a device is in landscape mode and fullscreen modal some dates are unreachable because the scroll function is not working.

Chrome dev toolbar device GIF screenshot:
![85eq0LtthW](https://user-images.githubusercontent.com/14150736/63339554-b95e4b80-c377-11e9-951e-0cf9a7e5d01f.gif)

Actual Android Device Screenshot:
![Screenshot_20190820-182751_Ionic_4_Template 1](https://user-images.githubusercontent.com/14150736/63339874-6c2ea980-c378-11e9-80de-2f43d884a4ee.jpg)

**Comment by SauloLauers1982** [comment]
Is it necessary to be fullscreen? If you reduce it a litte bit it will fit I guess.

**Comment by chintan13** [comment]
We have added some fixing in 1.4.2 for this. But for this to work please make sure to add below in global.scss
```
.li-ionic4-datePicker {
    .modal-wrapper {
        height: 470px;
        max-height: 100%;
        width: 312px;
    }
}
```
