### ISSUE TITLE
You can't choose the color of the letter of highlightedDates field.

### ISSUE THREAD

**Issue by SauloLauers1982** [logisticinfotech/ionic4-datepicker#35]
The highlightedDates field allow only 2 paramters, date and color, but I think that we should have backgroundColor and fontColor.

Yours,

**Comment by chintan13** [comment]
We have now implemented this feature now you will be able to specify color just like this
```
highlightedDates: [
    { date: new Date('2019-09-10'), color: '#ee88bf', fontColor: '#fff' },
    { date: new Date('2019-09-12'), color: '#50f2b1', fontColor: '#fff' },
]
```
Please notice we have added fontColor here.
