### ISSUE TITLE
Highlight all sunday's of each month

### ISSUE THREAD

**Issue by atifgulzar** [logisticinfotech/ionic4-datepicker#37]
Hi 
Hope you all are good and doing well. 

I want to highlight all Sunday's of the each month in different color ( like in red ). below image is just an example. 
Overall component is good and working fine. 
Thanks to the creator and contributors. 

<img width="73" alt="Screenshot 2019-08-31 at 10 35 03 AM" src="https://user-images.githubusercontent.com/572680/64059699-042f5d00-cbdb-11e9-971c-7973576e40f7.png">

**Comment by digvijayLogistic** [comment]
Hello @atifgulzar ,
Please check this screenshot , and what you want is same or any changes in that.

![image_2019_09_02T14_06_12_158Z](https://user-images.githubusercontent.com/46132367/64177876-0107cb80-ce7e-11e9-8ef8-51852a9ba42f.png)

**Comment by atifgulzar** [comment]
Hi  @digvijayLogistic 

Apologise for late reply. Yes this is what I want. Can you please help me set this Sunday's highlight setting. Thanks

**Comment by digvijayLogistic** [comment]
hello @atifgulzar ,

Now, this feature is not available, but its prototype is ready for an update, So, please wait sometime we add this feature in our next releases as soon as possible.
Thank You.

**Comment by atifgulzar** [comment]
Okay Thanks for informing me.
Hope the new release bring more exciting enhancements and improvements.
