### ISSUE TITLE
Error while change in date format

### ISSUE THREAD

**Issue by skandaapriya** [logisticinfotech/ionic4-datepicker#6]
Working only with date format yyyy-MM-dd but not with dd-MM-yyyy. First time selection works fine but when selection has to be changed appears as below.  
![image](https://user-images.githubusercontent.com/34448637/51682876-7ec54800-200e-11e9-855d-83896072c634.png)

**Comment by AdemilsonMarsiglio** [comment]
For me also gives the error. But in my case, I've changed the monthsList.

My options its here:

datePickerObj: any = {
        closeOnSelect: true,
        setLabel: 'OK',
        todayLabel: 'Hoje',
        closeLabel: 'Fechar',
        titleLabel: 'Selecione uma data',
        monthsList: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
        weeksList: ["D", "S", "T", "Q", "Q", "S", "S"],
        clearButton : false ,
    };

**Comment by AdemilsonMarsiglio** [comment]
Not work for me.

If date formatted pt-br, specifically month, don't work.


<img width="1153" alt="print-error" src="https://user-images.githubusercontent.com/11741695/51790015-ee564700-2176-11e9-8408-20dad7f1e14b.png">

<img width="1153" alt="print error 2" src="https://user-images.githubusercontent.com/11741695/51790018-fa420900-2176-11e9-93da-4b3dd6f6240a.png">
