### ISSUE TITLE
Clear button is not in the right position 

### ISSUE THREAD

**Issue by welshcathy** [logisticinfotech/ionic4-datepicker#9]
Hiya,

Thank you for creating this - it's exactly what I need!

But I find that the clear button is running wild in the screen.

See this repo 
https://github.com/welshcathy/ionic-4-bugs

On the home page you can see that the clear button is not where it is meant to be.
<img width="310" alt="ionic_app" src="https://user-images.githubusercontent.com/895309/52799540-ebfa5500-3071-11e9-9629-cb58a7264e13.png">

Work around for now is to set clearButton: false in home.page.ts.
But I'd like to use the clear button!

**Comment by chintan13** [comment]
Please wrap that ion-input like below:

<ion-item>
   <ion-input [(ngModel)]="mydate1" readonly [liIonic4Datepicker]="datePickerObj"></ion-input>
</ion-item>

<ion-grid>
  <ion-row>
    <ion-col>
      <ion-input [(ngModel)]="mydate2" readonly [liIonic4Datepicker]="datePickerObj"></ion-input>
    </ion-col>
  </ion-row>
</ion-grid>
